function paths=get_paths_old()
   %paths.datadir = '/data/symons/NH_old_data/mat/';
   paths.datadir = '/data/symons/NH_old_data/mat/good/';
   paths.imagedir = '/data/symons/NH_old_data/NH/regist/selected_data/good/';
   paths.astrodir = '/data/symons/NH_old_data/NH/regist/good/';
   paths.catdir = '/data/symons/NH_old_data/USNOB1_old/mat_files/';
   paths.maskdir = '/data/symons/NH_old_data/masks/';
   paths.selectmaskdir = '/data/symons/NH_old_data/select_masks/';
   paths.ghostdir = '/data/symons/NH_old_data/ghosts/';
   paths.magdir = '/data/symons/NH_old_data/mags/';
   paths.histdir = '/data/symons/NH_old_data/hist/';
   paths.ghosthistdir = '/data/symons/NH_old_data/ghosthist/';
   %paths.darkfitsdir = '/data/zemcov/NH/NH/launch/dark/selected_data/';
   paths.darkdir = '/data/symons/NH_old_data/dark/';
   paths.engdir = '/data/symons/NH_old_data/eng/data/';
   paths.tridir = '/data/symons/NH_old_data/trilegal/';
   paths.mandir = '/data/symons/NH_old_data/manmask/';
   paths.gscdir = '/data/symons/NH_old_data/GSCII/';
   paths.gaiadir = '/data/symons/NH_old_data/gaia/';
   paths.irisdir = '/data/symons/NH_old_data/IRIS/';
   paths.planckdir = '/data/symons/NH_old_data/planck/';
   paths.dgldir = '/data/symons/NH_old_data/dgl/';
   paths.simgaiadir = '/data/symons/NH_old_data/sims_gaia/';
   paths.simusnobdir = '/data/symons/NH_old_data/sims_usnob/';
end
